name: VanishV2
main: sqrrl\VanishV2\VanishV2
api: 5.0.0
extensions:
  Core: '>=8.0'
version: "4.0.2"
author: sqrrl
commands:
  vanish:
    description: "Enter vanish mode"
    permission: "vanish.use"
    aliases:
    - v
permissions:
  vanish.use:
    description: "Permission to use the vanish command"
    default: op
  vanish.use.other:
    description: "Permission to vanish other player"
    default: op
  vanish.see:
     description: "Permission to see vanished players"
     default: op
  vanish.silent:
    description: "Permission to silently join the server"
    default: op
  vanish.attack:
    description: "allows you to attack players while vanished"
    default: op
