name: VanishV2
main: superbobby\VanishV2\VanishV2
api: 3.0.0
mcpe-protocol: [407]
version: "1.8"
author: superbobby
commands:
  vanish:
    description: "Enter vanish mode"
    permission: "vanish.use"
    aliases:
    - v
permissions:
  vanish.use:
    description: "Permission to use the vanish command"
    default: op
  vanish.see:
     description: "Permission to see vanished players"
     default: op
